version: '3'

services:
  workspace:
    volumes:
      - applications-sync:/var/www:nocopy
      - docker-in-docker:/certs/client
      - ./php-worker/supervisord.d:/etc/supervisord.d
  php-fpm:
    volumes:
      - applications-sync:/var/www:nocopy
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - docker-in-docker:/certs/client
  nginx:
    volumes:
      - applications-sync:/var/www:nocopy
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
  mysql:
    volumes:
      - ~/.laradock/data/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  redis:
    volumes:
      - ~/.laradock/data/redis:/data
  rabbitmq:
    volumes:
      - ~/.laradock/data/rabbitmq:/var/lib/rabbitmq

volumes:
  applications-sync:
    external:
      name: "applications-docker-sync"
